In [72]:
# import libraries
import numpy as np
import pandas as pd

In [73]:
df=pd.read_csv("HousePricePrediction.csv")
df

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2914,160,RM,1936,Inside,Twnhs,7,1970,1970,CemntBd,0.0,546.0,NaN
2915,2915,160,RM,1894,Inside,TwnhsE,5,1970,1970,CemntBd,0.0,546.0,NaN
2916,2916,20,RL,20000,Inside,1Fam,7,1960,1996,VinylSd,0.0,1224.0,NaN
2917,2917,85,RL,10441,Inside,1Fam,5,1992,1992,HdBoard,0.0,912.0,NaN
2918,2918,60,RL,9627,Inside,1Fam,5,1993,1994,HdBoard,0.0,996.0,NaN

In [81]:
# Feature engineering
df.dropna(subset=['SalePrice'],inplace=True)
x=df.drop(["MSZoning","Exterior1st","BldgType","SalePrice"], axis=1)
y=df["SalePrice"]

In [68]:
# handle missing values in sale price target column
# df.dropna(subset=['SalePrice'])

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1455,60,RL,7917,Inside,1Fam,5,1999,2000,VinylSd,0.0,953.0,175000.0
1456,1456,20,RL,13175,Inside,1Fam,6,1978,1988,Plywood,163.0,1542.0,210000.0
1457,1457,70,RL,9042,Inside,1Fam,9,1941,2006,CemntBd,0.0,1152.0,266500.0
1458,1458,20,RL,9717,Inside,1Fam,6,1950,1996,MetalSd,1029.0,1078.0,142125.0
1459,1459,20,RL,9937,Inside,1Fam,6,1965,1965,HdBoard,290.0,1256.0,147500.0

In [69]:


print(x.columns)

Index(['Id', 'MSSubClass', 'MSZoning', 'LotArea', 'LotConfig', 'BldgType',
       'OverallCond', 'YearBuilt', 'YearRemodAdd', 'Exterior1st', 'BsmtFinSF2',
       'TotalBsmtSF'],
      dtype='object')

In [82]:
# encoding
x["LotConfig"]=x["LotConfig"].map({
    "Inside": 0,
    "Corner": 1,
    "CulDSac": 2,
    "FR2": 3,
    "FR3": 4
})

In [83]:
x

,Id,MSSubClass,LotArea,LotConfig,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF
0,0,60,8450,0,5,2003,2003,0.0,856.0
1,1,20,9600,3,8,1976,1976,0.0,1262.0
2,2,60,11250,0,5,2001,2002,0.0,920.0
3,3,70,9550,1,5,1915,1970,0.0,756.0
4,4,60,14260,3,5,2000,2000,0.0,1145.0
...,...,...,...,...,...,...,...,...,...
1455,1455,60,7917,0,5,1999,2000,0.0,953.0
1456,1456,20,13175,0,6,1978,1988,163.0,1542.0
1457,1457,70,9042,0,9,1941,2006,0.0,1152.0
1458,1458,20,9717,0,6,1950,1996,1029.0,1078.0
1459,1459,20,9937,0,6,1965,1965,290.0,1256.0

In [84]:
# test and training
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

In [85]:
x_train.head()

,Id,MSSubClass,LotArea,LotConfig,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF
254,254,20,8400,0,6,1957,1957,0.0,1314.0
1066,1066,60,7837,0,7,1993,1994,0.0,799.0
638,638,30,8777,0,7,1910,1950,0.0,796.0
799,799,50,7200,1,7,1937,1950,0.0,731.0
380,380,50,5000,0,6,1924,1950,0.0,1026.0

In [86]:
# Train the model
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [87]:
# prdict values
y_predict=model.predict(x_test)
y_predict

array([202134.89658497, 234062.96350862, 119778.59853648, 134568.6071156 ,
       262831.40276007, 127230.67755042, 186519.80833919, 157537.11031563,
       124387.34208883, 142222.68460711, 113207.89008487, 150856.83042595,
       115639.68353457, 246570.63903594, 196905.01034075, 190099.92294109,
       196238.40423275, 188819.08485223, 109945.322179  , 240606.14063634,
       170886.76391859, 197900.55033445, 193436.27088194, 172856.14875034,
       231297.03231059, 208779.63072591, 236468.1178096 , 130672.55404927,
       196969.9365469 , 237672.79248706, 117355.64957636, 210177.64463819,
       214940.27030272, 142805.49953192, 262103.58517536, 165309.68273005,
       157498.18524103, 196233.59130112, 236163.22835082,  66470.65274458,
       107555.63690666, 197140.38196457, 149782.38876598, 294847.42232411,
       143759.74047755,  83603.27464879, 127886.546015  , 157003.57039033,
       274017.891007  , 134304.45404327, 125635.31567747, 210225.76909391,
       116654.38454409, 212822.07106753, 195833.38009326, 265390.57182779,
       174228.67356959, 188551.89007391, 166844.98232189, 115711.13354731,
        80669.22172322, 180113.85902989, 220849.72894572, 256174.77738438,
       273310.00516826, 202516.87337824, 109814.26859703, 246768.63885118,
       189208.78629356, 180579.00958359,  97919.87241934, 139542.69813067,
       135766.19843579,  50987.39239781, 317967.51247795, 215629.79287023,
       229543.28148208, 218405.64245419, 144940.58096162, 152416.66888459,
       167465.52672593,  90612.26050037, 146442.41504195, 114196.46317009,
       156213.83821781, 158379.39486294, 220812.70137002, 214310.60714508,
       196004.78041067, 195751.85580181, 192499.18860636, 137069.46966894,
       172088.84835329, 190502.00707164, 215383.77221232, 234445.72781877,
       168922.01745453, 181558.2704669 , 246585.98308756, 178439.90353304,
       197862.84220686, 198599.53101942, 261730.71817063, 161959.13336089,
       211779.99795819, 147464.8553128 , 194486.08122835, 237419.29755295,
       193132.73817207, 163164.47291015,  50735.42788886, 170935.36433099,
       205360.52943369, 168284.26229035, 207746.9657222 , 153345.99680143,
       174907.75327187, 147594.18292618,  98790.55154822, 360504.10503247,
       174208.60249055, 195435.42373025, 192683.84049803, 160051.60209995,
       215836.90163166, 149471.71264795, 199548.09742583, 111532.0041618 ,
       217144.85034601, 157024.92958869, 191449.34619771, 276190.45840936,
       193171.70070986,  91044.0986269 ,  77432.59136391, 269170.27333819,
       270537.38433806, 160788.67176981, 251700.90342107, 321935.79042297,
       237307.93285833, 185291.00739535, 161837.49648303, 126491.44416344,
       175438.98228705, 144718.27820397, 167998.22021854, 242338.67889777,
       187937.89011773,  83935.74357664,  91642.47205943, 125935.0346635 ,
       246486.79780934, 157033.57575236, 106842.37631792, 161477.61641576,
       172441.50463783, 162520.34348187, 131587.63764684, 160400.23140144,
       231645.30399897, 176884.9897099 , 260366.39843351, 198305.3394583 ,
       113883.15658817, 200003.39066528, 195814.30123947, 249485.88631937,
       292681.42127382, 154175.97511074, 276154.00330749, 129994.90800876,
       111625.59068652, 142176.82505332, 250404.79868003,  71789.45186825,
       100035.9405941 , 207428.31426727, 151182.86852249, 182795.21774114,
       215682.78064434,  96168.85603257, 164528.67399312, 148138.14426668,
       214726.80090179,  87531.56546299, 252626.81399172, 236115.1447192 ,
       239594.38723697, 122476.14379255, 139664.25755847, 133715.07858027,
       114647.35982723, 184080.45307942, 232220.67119867, 179310.32557546,
       225597.50164692,  79115.93252555, 197674.48393105,  98239.82295961,
       272568.86121398, 195070.79425678, 141377.08793868, 234940.01751315,
       230173.49857848, 144631.61448175, 206499.96649142, 161831.31457515,
       161167.18437129, 142782.07735389, 172019.55112898, 141450.81596944,
       136920.95616014, 180178.95945344, 229997.69600028, 254576.71490163,
       229121.36016656, 152661.52198546, 132237.0461454 ,  98495.54927116,
       157774.87422101, 235769.50561603, 205802.9858349 , 101448.93868155,
       246105.03343931, 204735.60613655,  81469.22165961, 146550.48113036,
       183712.16033114,  98908.27463137, 114092.85401666, 169762.31783708,
       134247.46561566, 160880.30848264, 185759.22367967, 143275.21820141,
       224370.92560304, 193805.50235512, 203613.76066871, 167196.11763662,
       149180.37918786, 183311.05172709, 214361.65705932, 248797.22088346,
       163480.23612482, 164482.72383847, 155981.07141273, 200472.11267318,
       178863.58688852, 103245.63593365, 205928.59287542, 151110.22797109,
       142039.65966473,  89433.30793046, 160475.03491823, 172047.55275145,
       159489.91908487, 142650.06821655, 171825.87683726, 214543.42269048,
       285785.26025071, 190681.21058265, 150911.73373929, 230120.8852277 ,
       265304.58239166, 214103.51045939, 217613.7434412 , 195589.19069096,
       136960.57126931, 157119.71159016, 295272.43667351, 216542.98660621,
       219912.65822324, 114872.43718574,  78573.75259746, 162479.35489492,
       204744.00284379, 278886.60193405, 251458.48445683, 127505.69401383,
       207302.81767394, 140575.09546537, 194455.29746126, 160756.77560462,
       266187.80919863, 201640.50075927, 204935.84235151, 164426.86355543,
       256234.12995462, 189843.94592008, 105655.59908434, 157098.3355732 ])

In [88]:
# evaluate the model
from sklearn.metrics import r2_score
r2=r2_score(y_test, y_predict)
print(r2)

0.5755410060459651